### ISSUE TITLE
To-do

### ISSUE THREAD

**Issue by MartinSchobben** [irods/irods_client_library_rirods#39]
- [x] Update links Description
- [x] Change base plot example vignettes

**Comment by mstfdkmn** [comment]
Perhaps the new logo can be scaled down to make it fitted in the area between the main title and "installation".
https://github.com/irods/irods_client_library_rirods#installation

**Comment by montesmariana** [comment]
- [ ] Refit logo size and logo color (#40)
